---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
    - govcloud.repo-epel
    - { role: govcloud.common, users: [{ username: vagrant }] }
    - govcloud.security
    - { role: govcloud.chrome, when: DESKTOP }
    - { role: govcloud.vscode, when: DESKTOP }
    - { role: govcloud.xrdp, when: DESKTOP }
