---
- hosts: localhost
  connection: local
  gather_facts: true
  become: true
  roles:
    - govcloud.repo-epel
    - govcloud.common
    - govcloud.security
    - { role: govcloud.gtk-theme, when: DESKTOP }
    - { role: govcloud.chrome, when: DESKTOP }
    - { role: govcloud.vscode, when: DESKTOP }
    - { role: govcloud.xrdp, when: DESKTOP }
